# Numpy

-  NumPy is used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy is short for "Numerical Python"

- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [5]:
#Installation of NumPy

import numpy 

In [6]:
#how to create array using numpy
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [4]:
type(arr)

numpy.ndarray

In [7]:
#NumPy is usually imported under the np alias.
import numpy as np

In [8]:
#1-D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [93]:
import pandas as pd
print(pd.__version__)

1.1.3


In [94]:
print(np.__version__)

1.19.2


In [10]:
#2-D array
#An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#3-D array
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
#Check Number of Dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
arr.ndim

3

In [97]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("Dimension:", arr.ndim)

[[[[[1 2 3 4]]]]]
Dimension: 5


- Indexing -

In [20]:
#Indexing
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [21]:
arr[1]

2

In [22]:
print(arr[2] + arr[3])

7


In [98]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[1, 4])

2nd element on 1st dim:  10


In [25]:
#accessing 3D array's elements
#Access the third element of the second array of the first array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [26]:
#Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


- Slicing

- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [28]:
print(arr[4:])

[5 6 7]


In [29]:
print(arr[:4])

[1 2 3 4]


In [30]:
#Negative Slicing
print(arr[-3:-1])

[5 6]


In [36]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6])

In [39]:
#step
print(arr[1:5:2])

[2 4]


In [40]:
#Slicing 2-D Arrays
#From the second array, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


- Copy

In [41]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


- View


In [42]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [43]:
#Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


- The copy returns None.
- The view returns the original array.

In [45]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


- The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

In [52]:
#Iterating
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [51]:
#list comprehensions
[i for i in arr ]

[1, 2, 3]

In [60]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


### nditer

In [61]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr.ndim

3

In [62]:
#Iterate through 3D array
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Join two arrays

In [64]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))


In [65]:
arr

array([1, 2, 3, 4, 5, 6])

In [66]:
#2D
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [69]:
arr1 = np.array([[1, 2], [3, 4]])


In [72]:
# Joining Arrays Using Stack Functions
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [77]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [99]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


### split

In [79]:
#Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [80]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Search

In [82]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


- The example above will return a tuple: (array([3, 5, 6],)

- ich means that the value 4 is present at index 3, 5, and 6.

### Sort

In [84]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


### Random Numbers in NumPy

- Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [88]:
#Generate a random integer from 0 to 100
from numpy import random
x = random.randint(100)
print(x)

36


In [89]:
#The random module's rand() method returns a random float between 0 and 1.
x = random.rand()
print(x)

0.08707041347703404


In [90]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
x=random.randint(100, size=(5))

print(x)

[19 90 28 64 76]


In [91]:
#generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))
print(x)

[[61 12 39 49 85]
 [80 79 76 10 66]
 [35 69 30  9 28]]
